spring:
  application:
    name: pay-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: 8082
finance:
  api:
    base-url: ${FINANCE_API_BASE_URL:https://finopenapi.ssafy.io}
