spring:
  application:
    name: pay-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: 8082
finance:
  api:
    base-url: ${FINANCE_API_BASE_URL:https://finopenapi.ssafy.io}
