### AUTH-03 은행 선택/계좌 등록
POST http://localhost:8080/api/v1/auth/bank-accounts
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "bankCode": "088",
  "accountNo": "1234567890123456"
}

### AUTH-04 1원 인증
POST http://localhost:8080/api/v1/auth/bank-accounts/10/verify-1won
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "verificationCode": "1234"
}

### AUTH-09 등록 계좌 삭제
POST http://localhost:8080/api/v1/auth/bank-accounts/10/delete
Authorization: Bearer {{accessToken}}
