spring:
  application:
    name: gateway-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

server:
  port: 8080
