eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

spring:
  cloud:
    gateway:
      routes:
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/api/v1/auth/**, /api/v1/home/**, /api/v1/profiles/**

        - id: core-service-swagger-ui
          uri: lb://core-service
          predicates:
            - Path=/api/auth/swagger-ui/**
          filters:
            - RewritePath=/api/auth/swagger-ui(?<segment>/?.*), /swagger-ui${segment}

        - id: core-service-api-docs
          uri: lb://core-service
          predicates:
            - Path=/api/auth/v3/api-docs/**
          filters:
            - RewritePath=/api/auth/v3/api-docs(?<segment>/?.*), /v3/api-docs${segment}

        - id: pay-service
          uri: lb://pay-service
          predicates:
            - Path=/api/v1/rooms/**, /api/v1/payments/**, /api/v1/settlements/**, /api/v1/expenses/**

        - id: pay-service-swagger-ui
          uri: lb://pay-service
          predicates:
            - Path=/api/payment/swagger-ui/**
          filters:
            - RewritePath=/api/payment/swagger-ui(?<segment>/?.*), /swagger-ui${segment}

        - id: pay-service-api-docs
          uri: lb://pay-service
          predicates:
            - Path=/api/payment/v3/api-docs/**
          filters:
            - RewritePath=/api/payment/v3/api-docs(?<segment>/?.*), /v3/api-docs${segment}

        - id: insight-service
          uri: lb://insight-service
          predicates:
            - Path=/api/v1/analytics/**, /api/v1/games/**

        - id: insight-service-swagger-ui
          uri: lb://insight-service
          predicates:
            - Path=/api/analytics/swagger-ui/**
          filters:
            - RewritePath=/api/analytics/swagger-ui(?<segment>/?.*), /swagger-ui${segment}

        - id: insight-service-api-docs
          uri: lb://insight-service
          predicates:
            - Path=/api/analytics/v3/api-docs/**
          filters:
            - RewritePath=/api/analytics/v3/api-docs(?<segment>/?.*), /v3/api-docs${segment}

jwt:
  secret: ${JWT_SECRET}
