eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: core-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.duckchi.core.*"
    listener:
      ack-mode: manual_immediate


jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}

# [External API] 외부 금융망 연동 설정
finance:
  api:
    base-url: https://finopenapi.ssafy.io
    key: ${FINANCE_API_KEY}

security:
  pay-password:
    pepper: ${PAY_PASSWORD_PEPPER}
    bcrypt-strength: 12

firebase:
  admin-sdk-path: ${FIREBASE_PROD_ACCOUNT_PATH}

swagger:
  server-url: ${SWAGGER_SERVER_URL:https://j14c102.p.ssafy.io}

springdoc:
  swagger-ui:
    config-url: /api/auth/v3/api-docs/swagger-config
    url: /api/auth/v3/api-docs
